  
server:
  port: 9001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userservice_test?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Welcome@01
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
    initialization-mode: never
    platform: mysql
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      

check-user-scopes: true